assgn/assgn/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('college.urls'))
]

assgn/college/urls.py
from . import views
from django.urls import path

app_name = "college"

urlpatterns=[
    path('',views.index,name="colleges"),
    path('students/<int:college_id>/',views.students,name="students"),
]

assgn/college/models.py
from django.db import models

# Create your models here.
class College(models.Model):
    college_name=models.CharField(max_length=100,unique=True)
    college_address=models.CharField(max_length=500,null=True)
    def __str__(self):
        return self.college_name

class Student(models.Model):
    college_name=models.ForeignKey(College,on_delete=models.CASCADE)
    student_name=models.CharField(max_length=100)
    branch=models.CharField(max_length=100)
    first_year=models.IntegerField(null=True)
    second_year=models.IntegerField(null=True)
    third_year=models.IntegerField(null=True)
    fourth_year=models.IntegerField(null=True)

    def __str__(self):
        return self.student_name

assgn/college/views.py
from django.shortcuts import render
from .models import College,Student

# Create your views here.
def index(request):
    colleges=list(College.objects.all())
    context={'colleges' : colleges}
    return render(request,'college/index.html',context)
    
def students(request,college_id):
    college=College.objects.get(pk=college_id)
    college_students=list(Student.objects.filter(college_name=college))
    average_marks=[]
    for student in college_students:
        total_marks=student.first_year+student.second_year+student.third_year+student.fourth_year
        average=int(total_marks/4)
        average_marks.append(average)

    details=zip(college_students,average_marks)
    return render(request,'college/students.html',{'college':college,'details':details})

assgn/templates/college/index.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Welcome</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static "college/master.css" %}"/>
    </head>
    <body>
        <h1>Colleges</h1>
        {% for college in colleges %}
        <div class="card mx-auto" style="width: 40rem;">
            <div class="card-body">
                <h4 class="clg-names">{{college.college_name}}</h4>
                <h6 class="card-text">Address : </h6>
                <p class="card-text">{{college.college_address}}</p>
                <a href="{% url 'college:students' college.id %}" class="btn btn-primary">Visit</a>
            </div>
        </div>
        {% endfor %}          

    </body>
</html>

assgn/templates/college/students.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{{college.college_name}} Student Details</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static "college/master.css" %}"/>
    </head>
    <body>
        <h1>{{college.college_name}} - Student Details</h1>
        <div style="overflow-x:auto;">
        <table  class="students">
            <thread>
            <tr>
                <th>Name</th>
                <th>Dept</th>
                <th>1st Year</th>
                <th>2nd Year</th>
                <th>3rd Year</th>
                <th>4th Year</th>
                <th>Average Marks</th>
            </tr>
            </thread>
            <tbody>
            {% for i,j in details %}
            <tr>
                <td>{{i.student_name}}</td>
                <td>{{i.branch}}</td>
                <td>{{i.first_year}}</td>
                <td>{{i.second_year}}</td>
                <td>{{i.third_year}}</td>
                <td>{{i.fourth_year}}</td>
                <td>{{j}}

            </tr>

            {% endfor %}  
            </tbody>
        </table>

        </div>
                  

    </body>
</html>